project:
  type: website
  output-dir: _site
  title: "Live LLM-Enhanced Behavioral Decisions"
  resources:
    - ../figs
    - ../data

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Manuscript"
        href: main.qmd
      - text: "Blueprint"
        href: blueprint.md
      - text: "Conventions"
        href: conventions.md
      - text: "Repro Manual"
        href: repro_manual.qmd
      - text: "Decider Stub"
        href: methods/decider.md
      - text: "Py2 Client"
        href: methods/py2_client.md

format:
  html:
    theme: cosmo
    toc: true
